version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - yum update -y
      - yum install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Done

artifacts:
  files:
    - 'index.html'

